title: Portfolio
description: Portfolio of Jesus Daniel Gonzalez Rocha
theme: just-the-docs

url: https://just-the-docs.github.io
color_scheme: dark

aux_links:
  Github: https://github.com/Dan1543
  Linkedin: https://www.linkedin.com/in/jesus-daniel-gonzalez-rocha-93010b28b/?skipRedirect=true
#  Template Repository: https://github.com/just-the-docs/just-the-docs-template
